### ISSUE TITLE
00. Introduction

### ISSUE THREAD

**Issue by Vayel** [artragis/tutoriels-et-articles-les-nouveautes-de-la-version-159#1]
- Etat du module v1 des contenus
- Problèmes avec ce module v1

**Comment by GerardPaligot** [comment]
Peut-être faudrait-il détailler l'état du module v1 et énumérer les problèmes. Ca facilitera la rédaction.

**Comment by Vayel** [comment]
Ouep. Par contre, peut-être devrait-on dans un premier ce contenter de dire de quoi on va parler, avant de détailler ces points ?

**Comment by GerardPaligot** [comment]
Pour moi, une bonne introduction d'un articles :
1. Tu poses les bases. Tu expliques le contexte de ton sujet. Donc on aborde l'état du module v1 et ses problèmes puisque c'est fortement lié.
2. Tu commences à introduire le sujet de ton article, le module v2. Sans rentrer dans les détails, tu le présentes.
3. Tu expliques via un point par point le contenu des sections à venir.

**Comment by artragis** [comment]
Comme j'ai rédigé un premier jet d'intro, tu peux déjà regarder si ça correspond à ton cahier des charges.

**Comment by Situphen** [comment]
Perso j'aime pas trop l'idée de "Clem 2.0". Je trouve que c'est comme "web 2.0" et que ça ne représente pas grand chose au final.

**Comment by artragis** [comment]
c'est pour ça qu'il faut le garder :p

L'idée est juste de faire fun et de rendre un article technique un peu 
plus communautaire. Et puis c'est juste un déguisement de clem, pas un 
changement de mascotte complet.

**Comment by pierre-24** [comment]
Mmmh. D'habitude, j'aime bien écrire des textes dans le style que tu proposes, mais j'ai peur que ça nous déserve dans ce cas-ci. Comme la ZEP a une partie très "technique", ça fait effectivement mieux passer la pillule, si je puis dire, mais ça colle pas à l'intro, donc ça fait un peu artificiel. Non ?

**Comment by GerardPaligot** [comment]
Proposition d'introduction en partant des écrits d'artragis : https://github.com/artragis/tutoriels-et-articles-les-nouveautes-de-la-version-159/pull/9
